// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAppWithAuthenticationApi.Data;

#nullable disable

namespace WebAppWithAuthenticationApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260420144328_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("WebAppWithAuthenticationApi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Position")
                        .HasColumnType("longtext");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("RefreshTokenExpirationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "72a568297b6e492cb7159c92257d091e",
                            Email = "admin@email.com",
                            EmailConfirmed = false,
                            LastLoginDate = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LockoutEnabled = false,
                            Name = "John",
                            NormalizedEmail = "ADMIN@EMAIL.COM",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAIAAYagAAAAELBqe1NgUjUNqnZvM3XOzxCdspKAJQkM3OWjVDsF0wyKQVA+6r+huRE3hV0AOGKRpg==",
                            PhoneNumberConfirmed = false,
                            Position = "Software Engineer",
                            SecurityStamp = "f4d927c3e10a4865a9e3427f1020b941",
                            Status = 0,
                            Surname = "Doe",
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        },
                        new
                        {
                            Id = 2,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "72a568297b6e492cb7159c92257d091e",
                            Email = "m.rossi@email.com",
                            EmailConfirmed = false,
                            LastLoginDate = new DateTime(2026, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LockoutEnabled = false,
                            Name = "Marco",
                            NormalizedEmail = "M.ROSSI@EMAIL.COM",
                            NormalizedUserName = "M.ROSSI",
                            PasswordHash = "AQAAAAIAAYagAAAAELBqe1NgUjUNqnZvM3XOzxCdspKAJQkM3OWjVDsF0wyKQVA+6r+huRE3hV0AOGKRpg==",
                            PhoneNumberConfirmed = false,
                            Position = "Project Manager",
                            SecurityStamp = "f4d927c3e10a4865a9e3427f1020b941",
                            Status = 2,
                            Surname = "Rossi",
                            TwoFactorEnabled = false,
                            UserName = "m.rossi"
                        },
                        new
                        {
                            Id = 3,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "72a568297b6e492cb7159c92257d091e",
                            Email = "s.chen@email.com",
                            EmailConfirmed = false,
                            LastLoginDate = new DateTime(2026, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LockoutEnabled = false,
                            Name = "Sarah",
                            NormalizedEmail = "S.CHEN@EMAIL.COM",
                            NormalizedUserName = "S.CHEN",
                            PasswordHash = "AQAAAAIAAYagAAAAELBqe1NgUjUNqnZvM3XOzxCdspKAJQkM3OWjVDsF0wyKQVA+6r+huRE3hV0AOGKRpg==",
                            PhoneNumberConfirmed = false,
                            Position = "UI/UX Designer",
                            SecurityStamp = "f4d927c3e10a4865a9e3427f1020b941",
                            Status = 0,
                            Surname = "Chen",
                            TwoFactorEnabled = false,
                            UserName = "s.chen"
                        },
                        new
                        {
                            Id = 4,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "72a568297b6e492cb7159c92257d091e",
                            Email = "a.smith@email.com",
                            EmailConfirmed = false,
                            LastLoginDate = new DateTime(2026, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LockoutEnabled = false,
                            Name = "Alice",
                            NormalizedEmail = "A.SMITH@EMAIL.COM",
                            NormalizedUserName = "A.SMITH",
                            PasswordHash = "AQAAAAIAAYagAAAAELBqe1NgUjUNqnZvM3XOzxCdspKAJQkM3OWjVDsF0wyKQVA+6r+huRE3hV0AOGKRpg==",
                            PhoneNumberConfirmed = false,
                            Position = "DevOps Engineer",
                            SecurityStamp = "f4d927c3e10a4865a9e3427f1020b941",
                            Status = 1,
                            Surname = "Smith",
                            TwoFactorEnabled = false,
                            UserName = "a.smith"
                        },
                        new
                        {
                            Id = 5,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "72a568297b6e492cb7159c92257d091e",
                            Email = "h.tanaka@email.com",
                            EmailConfirmed = false,
                            LastLoginDate = new DateTime(2026, 4, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LockoutEnabled = false,
                            Name = "Hiroshi",
                            NormalizedEmail = "H.TANAKA@EMAIL.COM",
                            NormalizedUserName = "H.TANAKA",
                            PasswordHash = "AQAAAAIAAYagAAAAELBqe1NgUjUNqnZvM3XOzxCdspKAJQkM3OWjVDsF0wyKQVA+6r+huRE3hV0AOGKRpg==",
                            PhoneNumberConfirmed = false,
                            Position = "Backend Developer",
                            SecurityStamp = "f4d927c3e10a4865a9e3427f1020b941",
                            Status = 2,
                            Surname = "Tanaka",
                            TwoFactorEnabled = false,
                            UserName = "h.tanaka"
                        },
                        new
                        {
                            Id = 6,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "72a568297b6e492cb7159c92257d091e",
                            Email = "e.dubois@email.com",
                            EmailConfirmed = false,
                            LastLoginDate = new DateTime(2026, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LockoutEnabled = false,
                            Name = "Elena",
                            NormalizedEmail = "E.DUBOIS@EMAIL.COM",
                            NormalizedUserName = "E.DUBOIS",
                            PasswordHash = "AQAAAAIAAYagAAAAELBqe1NgUjUNqnZvM3XOzxCdspKAJQkM3OWjVDsF0wyKQVA+6r+huRE3hV0AOGKRpg==",
                            PhoneNumberConfirmed = false,
                            Position = "QA Analyst",
                            SecurityStamp = "f4d927c3e10a4865a9e3427f1020b941",
                            Status = 0,
                            Surname = "Dubois",
                            TwoFactorEnabled = false,
                            UserName = "e.dubois"
                        },
                        new
                        {
                            Id = 7,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "72a568297b6e492cb7159c92257d091e",
                            Email = "j.kowalski@email.com",
                            EmailConfirmed = false,
                            LastLoginDate = new DateTime(2026, 4, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LockoutEnabled = false,
                            Name = "Jan",
                            NormalizedEmail = "J.KOWALSKI@EMAIL.COM",
                            NormalizedUserName = "J.KOWALSKI",
                            PasswordHash = "AQAAAAIAAYagAAAAELBqe1NgUjUNqnZvM3XOzxCdspKAJQkM3OWjVDsF0wyKQVA+6r+huRE3hV0AOGKRpg==",
                            PhoneNumberConfirmed = false,
                            Position = "Frontend Developer",
                            SecurityStamp = "f4d927c3e10a4865a9e3427f1020b941",
                            Status = 1,
                            Surname = "Kowalski",
                            TwoFactorEnabled = false,
                            UserName = "j.kowalski"
                        },
                        new
                        {
                            Id = 8,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "72a568297b6e492cb7159c92257d091e",
                            Email = "l.garcia@email.com",
                            EmailConfirmed = false,
                            LastLoginDate = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LockoutEnabled = false,
                            Name = "Luis",
                            NormalizedEmail = "L.GARCIA@EMAIL.COM",
                            NormalizedUserName = "L.GARCIA",
                            PasswordHash = "AQAAAAIAAYagAAAAELBqe1NgUjUNqnZvM3XOzxCdspKAJQkM3OWjVDsF0wyKQVA+6r+huRE3hV0AOGKRpg==",
                            PhoneNumberConfirmed = false,
                            Position = "Data Scientist",
                            SecurityStamp = "f4d927c3e10a4865a9e3427f1020b941",
                            Status = 0,
                            Surname = "Garcia",
                            TwoFactorEnabled = false,
                            UserName = "l.garcia"
                        },
                        new
                        {
                            Id = 9,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "72a568297b6e492cb7159c92257d091e",
                            Email = "m.ahmed@email.com",
                            EmailConfirmed = false,
                            LastLoginDate = new DateTime(2026, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LockoutEnabled = false,
                            Name = "Mariam",
                            NormalizedEmail = "M.AHMED@EMAIL.COM",
                            NormalizedUserName = "M.AHMED",
                            PasswordHash = "AQAAAAIAAYagAAAAELBqe1NgUjUNqnZvM3XOzxCdspKAJQkM3OWjVDsF0wyKQVA+6r+huRE3hV0AOGKRpg==",
                            PhoneNumberConfirmed = false,
                            Position = "Systems Architect",
                            SecurityStamp = "f4d927c3e10a4865a9e3427f1020b941",
                            Status = 2,
                            Surname = "Ahmed",
                            TwoFactorEnabled = false,
                            UserName = "m.ahmed"
                        },
                        new
                        {
                            Id = 10,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "72a568297b6e492cb7159c92257d091e",
                            Email = "k.nielsen@email.com",
                            EmailConfirmed = false,
                            LastLoginDate = new DateTime(2026, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LockoutEnabled = false,
                            Name = "Kasper",
                            NormalizedEmail = "K.NIELSEN@EMAIL.COM",
                            NormalizedUserName = "K.NIELSEN",
                            PasswordHash = "AQAAAAIAAYagAAAAELBqe1NgUjUNqnZvM3XOzxCdspKAJQkM3OWjVDsF0wyKQVA+6r+huRE3hV0AOGKRpg==",
                            PhoneNumberConfirmed = false,
                            Position = "Business Analyst",
                            SecurityStamp = "f4d927c3e10a4865a9e3427f1020b941",
                            Status = 2,
                            Surname = "Nielsen",
                            TwoFactorEnabled = false,
                            UserName = "k.nielsen"
                        },
                        new
                        {
                            Id = 11,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "72a568297b6e492cb7159c92257d091e",
                            Email = "f.silva@email.com",
                            EmailConfirmed = false,
                            LastLoginDate = new DateTime(2026, 4, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LockoutEnabled = false,
                            Name = "Fernanda",
                            NormalizedEmail = "F.SILVA@EMAIL.COM",
                            NormalizedUserName = "F.SILVA",
                            PasswordHash = "AQAAAAIAAYagAAAAELBqe1NgUjUNqnZvM3XOzxCdspKAJQkM3OWjVDsF0wyKQVA+6r+huRE3hV0AOGKRpg==",
                            PhoneNumberConfirmed = false,
                            Position = "Cloud Engineer",
                            SecurityStamp = "f4d927c3e10a4865a9e3427f1020b941",
                            Status = 0,
                            Surname = "Silva",
                            TwoFactorEnabled = false,
                            UserName = "f.silva"
                        },
                        new
                        {
                            Id = 12,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "72a568297b6e492cb7159c92257d091e",
                            Email = "o.peters@email.com",
                            EmailConfirmed = false,
                            LastLoginDate = new DateTime(2026, 4, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LockoutEnabled = false,
                            Name = "Oliver",
                            NormalizedEmail = "O.PETERS@EMAIL.COM",
                            NormalizedUserName = "O.PETERS",
                            PasswordHash = "AQAAAAIAAYagAAAAELBqe1NgUjUNqnZvM3XOzxCdspKAJQkM3OWjVDsF0wyKQVA+6r+huRE3hV0AOGKRpg==",
                            PhoneNumberConfirmed = false,
                            Position = "Security Specialist",
                            SecurityStamp = "f4d927c3e10a4865a9e3427f1020b941",
                            Status = 2,
                            Surname = "Peters",
                            TwoFactorEnabled = false,
                            UserName = "o.peters"
                        },
                        new
                        {
                            Id = 13,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "72a568297b6e492cb7159c92257d091e",
                            Email = "y.kim@email.com",
                            EmailConfirmed = false,
                            LastLoginDate = new DateTime(2026, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LockoutEnabled = false,
                            Name = "Yuna",
                            NormalizedEmail = "Y.KIM@EMAIL.COM",
                            NormalizedUserName = "Y.KIM",
                            PasswordHash = "AQAAAAIAAYagAAAAELBqe1NgUjUNqnZvM3XOzxCdspKAJQkM3OWjVDsF0wyKQVA+6r+huRE3hV0AOGKRpg==",
                            PhoneNumberConfirmed = false,
                            Position = "Mobile Developer",
                            SecurityStamp = "f4d927c3e10a4865a9e3427f1020b941",
                            Status = 0,
                            Surname = "Kim",
                            TwoFactorEnabled = false,
                            UserName = "y.kim"
                        },
                        new
                        {
                            Id = 14,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "72a568297b6e492cb7159c92257d091e",
                            Email = "r.kumar@email.com",
                            EmailConfirmed = false,
                            LastLoginDate = new DateTime(2026, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LockoutEnabled = false,
                            Name = "Rohan",
                            NormalizedEmail = "R.KUMAR@EMAIL.COM",
                            NormalizedUserName = "R.KUMAR",
                            PasswordHash = "AQAAAAIAAYagAAAAELBqe1NgUjUNqnZvM3XOzxCdspKAJQkM3OWjVDsF0wyKQVA+6r+huRE3hV0AOGKRpg==",
                            PhoneNumberConfirmed = false,
                            Position = "Database Administrator",
                            SecurityStamp = "f4d927c3e10a4865a9e3427f1020b941",
                            Status = 1,
                            Surname = "Kumar",
                            TwoFactorEnabled = false,
                            UserName = "r.kumar"
                        },
                        new
                        {
                            Id = 15,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "72a568297b6e492cb7159c92257d091e",
                            Email = "b.wright@email.com",
                            EmailConfirmed = false,
                            LastLoginDate = new DateTime(2026, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LockoutEnabled = false,
                            Name = "Beatrice",
                            NormalizedEmail = "B.WRIGHT@EMAIL.COM",
                            NormalizedUserName = "B.WRIGHT",
                            PasswordHash = "AQAAAAIAAYagAAAAELBqe1NgUjUNqnZvM3XOzxCdspKAJQkM3OWjVDsF0wyKQVA+6r+huRE3hV0AOGKRpg==",
                            PhoneNumberConfirmed = false,
                            Position = "Product Owner",
                            SecurityStamp = "f4d927c3e10a4865a9e3427f1020b941",
                            Status = 0,
                            Surname = "Wright",
                            TwoFactorEnabled = false,
                            UserName = "b.wright"
                        },
                        new
                        {
                            Id = 16,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "72a568297b6e492cb7159c92257d091e",
                            Email = "t.muller@email.com",
                            EmailConfirmed = false,
                            LastLoginDate = new DateTime(2026, 4, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LockoutEnabled = false,
                            Name = "Thomas",
                            NormalizedEmail = "T.MULLER@EMAIL.COM",
                            NormalizedUserName = "T.MULLER",
                            PasswordHash = "AQAAAAIAAYagAAAAELBqe1NgUjUNqnZvM3XOzxCdspKAJQkM3OWjVDsF0wyKQVA+6r+huRE3hV0AOGKRpg==",
                            PhoneNumberConfirmed = false,
                            Position = "Scrum Master",
                            SecurityStamp = "f4d927c3e10a4865a9e3427f1020b941",
                            Status = 0,
                            Surname = "Müller",
                            TwoFactorEnabled = false,
                            UserName = "t.muller"
                        },
                        new
                        {
                            Id = 17,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "72a568297b6e492cb7159c92257d091e",
                            Email = "i.popov@email.com",
                            EmailConfirmed = false,
                            LastLoginDate = new DateTime(2026, 4, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LockoutEnabled = false,
                            Name = "Igor",
                            NormalizedEmail = "I.POPOV@EMAIL.COM",
                            NormalizedUserName = "I.POPOV",
                            PasswordHash = "AQAAAAIAAYagAAAAELBqe1NgUjUNqnZvM3XOzxCdspKAJQkM3OWjVDsF0wyKQVA+6r+huRE3hV0AOGKRpg==",
                            PhoneNumberConfirmed = false,
                            Position = "Network Engineer",
                            SecurityStamp = "f4d927c3e10a4865a9e3427f1020b941",
                            Status = 1,
                            Surname = "Popov",
                            TwoFactorEnabled = false,
                            UserName = "i.popov"
                        },
                        new
                        {
                            Id = 18,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "72a568297b6e492cb7159c92257d091e",
                            Email = "c.santos@email.com",
                            EmailConfirmed = false,
                            LastLoginDate = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LockoutEnabled = false,
                            Name = "Clara",
                            NormalizedEmail = "C.SANTOS@EMAIL.COM",
                            NormalizedUserName = "C.SANTOS",
                            PasswordHash = "AQAAAAIAAYagAAAAELBqe1NgUjUNqnZvM3XOzxCdspKAJQkM3OWjVDsF0wyKQVA+6r+huRE3hV0AOGKRpg==",
                            PhoneNumberConfirmed = false,
                            Position = "Software Engineer",
                            SecurityStamp = "f4d927c3e10a4865a9e3427f1020b941",
                            Status = 0,
                            Surname = "Santos",
                            TwoFactorEnabled = false,
                            UserName = "c.santos"
                        },
                        new
                        {
                            Id = 19,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "72a568297b6e492cb7159c92257d091e",
                            Email = "v.nguyen@email.com",
                            EmailConfirmed = false,
                            LastLoginDate = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LockoutEnabled = false,
                            Name = "Vinh",
                            NormalizedEmail = "V.NGUYEN@EMAIL.COM",
                            NormalizedUserName = "V.NGUYEN",
                            PasswordHash = "AQAAAAIAAYagAAAAELBqe1NgUjUNqnZvM3XOzxCdspKAJQkM3OWjVDsF0wyKQVA+6r+huRE3hV0AOGKRpg==",
                            PhoneNumberConfirmed = false,
                            Position = "Machine Learning Engineer",
                            SecurityStamp = "f4d927c3e10a4865a9e3427f1020b941",
                            Status = 2,
                            Surname = "Nguyen",
                            TwoFactorEnabled = false,
                            UserName = "v.nguyen"
                        },
                        new
                        {
                            Id = 20,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "72a568297b6e492cb7159c92257d091e",
                            Email = "g.morris@email.com",
                            EmailConfirmed = false,
                            LastLoginDate = new DateTime(2026, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LockoutEnabled = false,
                            Name = "Grace",
                            NormalizedEmail = "G.MORRIS@EMAIL.COM",
                            NormalizedUserName = "G.MORRIS",
                            PasswordHash = "AQAAAAIAAYagAAAAELBqe1NgUjUNqnZvM3XOzxCdspKAJQkM3OWjVDsF0wyKQVA+6r+huRE3hV0AOGKRpg==",
                            PhoneNumberConfirmed = false,
                            Position = "Technical Writer",
                            SecurityStamp = "f4d927c3e10a4865a9e3427f1020b941",
                            Status = 0,
                            Surname = "Morris",
                            TwoFactorEnabled = false,
                            UserName = "g.morris"
                        },
                        new
                        {
                            Id = 21,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "72a568297b6e492cb7159c92257d091e",
                            Email = "d.patel@email.com",
                            EmailConfirmed = false,
                            LastLoginDate = new DateTime(2026, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LockoutEnabled = false,
                            Name = "Deepak",
                            NormalizedEmail = "D.PATEL@EMAIL.COM",
                            NormalizedUserName = "D.PATEL",
                            PasswordHash = "AQAAAAIAAYagAAAAELBqe1NgUjUNqnZvM3XOzxCdspKAJQkM3OWjVDsF0wyKQVA+6r+huRE3hV0AOGKRpg==",
                            PhoneNumberConfirmed = false,
                            Position = "Fullstack Developer",
                            SecurityStamp = "f4d927c3e10a4865a9e3427f1020b941",
                            Status = 1,
                            Surname = "Patel",
                            TwoFactorEnabled = false,
                            UserName = "d.patel"
                        },
                        new
                        {
                            Id = 22,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "72a568297b6e492cb7159c92257d091e",
                            Email = "z.jones@email.com",
                            EmailConfirmed = false,
                            LastLoginDate = new DateTime(2026, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LockoutEnabled = false,
                            Name = "Zoe",
                            NormalizedEmail = "Z.JONES@EMAIL.COM",
                            NormalizedUserName = "Z.JONES",
                            PasswordHash = "AQAAAAIAAYagAAAAELBqe1NgUjUNqnZvM3XOzxCdspKAJQkM3OWjVDsF0wyKQVA+6r+huRE3hV0AOGKRpg==",
                            PhoneNumberConfirmed = false,
                            Position = "Project Coordinator",
                            SecurityStamp = "f4d927c3e10a4865a9e3427f1020b941",
                            Status = 2,
                            Surname = "Jones",
                            TwoFactorEnabled = false,
                            UserName = "z.jones"
                        },
                        new
                        {
                            Id = 23,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "72a568297b6e492cb7159c92257d091e",
                            Email = "p.larsen@email.com",
                            EmailConfirmed = false,
                            LastLoginDate = new DateTime(2026, 4, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LockoutEnabled = false,
                            Name = "Pia",
                            NormalizedEmail = "P.LARSEN@EMAIL.COM",
                            NormalizedUserName = "P.LARSEN",
                            PasswordHash = "AQAAAAIAAYagAAAAELBqe1NgUjUNqnZvM3XOzxCdspKAJQkM3OWjVDsF0wyKQVA+6r+huRE3hV0AOGKRpg==",
                            PhoneNumberConfirmed = false,
                            Position = "Human Resources",
                            SecurityStamp = "f4d927c3e10a4865a9e3427f1020b941",
                            Status = 0,
                            Surname = "Larsen",
                            TwoFactorEnabled = false,
                            UserName = "p.larsen"
                        },
                        new
                        {
                            Id = 24,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "72a568297b6e492cb7159c92257d091e",
                            Email = "w.clark@email.com",
                            EmailConfirmed = false,
                            LastLoginDate = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LockoutEnabled = false,
                            Name = "William",
                            NormalizedEmail = "W.CLARK@EMAIL.COM",
                            NormalizedUserName = "W.CLARK",
                            PasswordHash = "AQAAAAIAAYagAAAAELBqe1NgUjUNqnZvM3XOzxCdspKAJQkM3OWjVDsF0wyKQVA+6r+huRE3hV0AOGKRpg==",
                            PhoneNumberConfirmed = false,
                            Position = "IT Manager",
                            SecurityStamp = "f4d927c3e10a4865a9e3427f1020b941",
                            Status = 1,
                            Surname = "Clark",
                            TwoFactorEnabled = false,
                            UserName = "w.clark"
                        },
                        new
                        {
                            Id = 25,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "72a568297b6e492cb7159c92257d091e",
                            Email = "k.adhikari@email.com",
                            EmailConfirmed = false,
                            LastLoginDate = new DateTime(2026, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LockoutEnabled = false,
                            Name = "Kiran",
                            NormalizedEmail = "K.ADHIKARI@EMAIL.COM",
                            NormalizedUserName = "K.ADHIKARI",
                            PasswordHash = "AQAAAAIAAYagAAAAELBqe1NgUjUNqnZvM3XOzxCdspKAJQkM3OWjVDsF0wyKQVA+6r+huRE3hV0AOGKRpg==",
                            PhoneNumberConfirmed = false,
                            Position = "Embedded Systems Dev",
                            SecurityStamp = "f4d927c3e10a4865a9e3427f1020b941",
                            Status = 1,
                            Surname = "Adhikari",
                            TwoFactorEnabled = false,
                            UserName = "k.adhikari"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("WebAppWithAuthenticationApi.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("WebAppWithAuthenticationApi.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebAppWithAuthenticationApi.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("WebAppWithAuthenticationApi.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
